### ISSUE TITLE
Dokany 0.8.0-RC3 ZwCreateFile gets called with invalid FileName argument

### ISSUE THREAD

**Issue by jgressmann** [dokan-dev/dokany#120]
Hi all,

I run into this issue when renaming a file in to root directory (e.g. \a.txt -> \b.txt). Renames in subdirectories don't seem to be affected. I assume the OpenDirectory call appears to be issued as part of the 'need to move file or rename file' resolution. Anyhow when OpenDirectory is called the parameter FileName points to an empty string. The code below works for me as a quick fix. 

I am on Win7, 64Bit running a 32Bit app.

Cheers,
Jean

```
NTSTATUS 
DokanFileSystem::OpenDirectory(LPCWSTR FileName, PDOKAN_FILE_INFO FileInfo) {
    NTSTATUS result = STATUS_SUCCESS;
    LPCWSTR x = FileName;
    std::wstring fixed;
    if (!*FileName) {
        fixed = L"\\";
        fixed += FileName + 1;
        x = fixed.c_str();
    }

    ....
}
```

**Comment by Liryna** [comment]
Hi @jgressmann ,

In dokan 0.8.0-RC3 there is no more OpenDirectory.
See: https://github.com/dokan-dev/dokany/releases/tag/v0.8.0-RC3
`CreateDirectory & OpenDirectory have been merged with CreateFileW `

**Comment by jgressmann** [comment]
My bad,  I probably have RC2 installed

**Comment by Liryna** [comment]
:smile: 
Try with the RC3, I think something that sounds like what you have report has been fixed in it.

**Comment by jgressmann** [comment]
Hi,

issue still present in RC3 except it now hits in ZwCreateFile.

Cheers,
Jean
```
NTSTATUS 
DokanFileSystem::ZwCreateFile(
        PCWSTR FileName,
        PDOKAN_IO_SECURITY_CONTEXT SecurityContext,
        ACCESS_MASK DesiredAccess,
        ULONG FileAttributes,
        ULONG ShareAccess,
        ULONG CreateDisposition,
        ULONG CreateOptions,
        PDOKAN_FILE_INFO FileInfo) {
    NTSTATUS result = STATUS_SUCCESS;

    DWORD fileAttributesAndFlags, creationDisposition;
    DokanMapKernelToUserCreateFileFlags(
      FileAttributes, CreateOptions, CreateDisposition, &fileAttributesAndFlags,
      &creationDisposition);

    PCWSTR x = FileName;
    std::wstring fixed;
    if (!*FileName) {
        fixed = L"\\";
        fixed += FileName + 1;
        x = fixed.c_str();
    }

    ....
}
```

**Comment by Liryna** [comment]
Could you give the command that you are using with mirror.exe and also the DOS command to reproduce the issue ?

```
>mirror.exe /r C:\Users\Liryna\Desktop /l m

>m:
>move a.txt b.txt
 1 file(s) moved.
>rename b.txt a.txt
>
```

I cannot reproduce it with the mirror in windows 10.

**Comment by jgressmann** [comment]
Hi,

the problem is also present in mirror.c (MirrorCreateFile) but is mask by
the way file path is manipulated and then passed to CreateFile.

You can reproduce the bug like so:

1. put this snippet at the begin of MirrorCreateFile and place a breakpoint
on the print line
-------SNIP------------
if (!*FileName) {
    fprintf(stderr, "No FileName\n");
}
-------SNIP------------

2. Mount a directory. I used the options /r c:\temp /l j
3. Using Explorer, navigate to the drive
4. Right-click and select Create new folder
5. Enter a name for the folder.
6. The breakpoint should be hit.

Cheers,
Jean

**Comment by Liryna** [comment]
The name is provided directly by windows kernel.
I don't think it is a good idea to change the windows behaviour, it could break other features.

**Comment by viciousviper** [comment]
For what it's worth:
The same anomalous behavior can be examined in the Dokan.NET test suite in 
https://github.com/viciousviper/dokan-dotnet/blob/master/DokanNet.Tests/DirectoryInfoTest.cs (lines 748 and 822).
I'd expect to see `\` here as `path` parameter in the calls to `CreateFile(...)`, but it is `string.Empty` instead.

**Comment by Liryna** [comment]
We have already try to add a `\` but it has been revert
https://github.com/dokan-dev/dokany/commit/4496617e47dabf2123020e7732ddc15264005260

**Comment by jgressmann** [comment]
Well, it looks like I'll just have to live with it.
Thanks for looking into this.

Cheers,
Jean
