### ISSUE TITLE
Win7 - mirror.exe without administrative privileges, running executables

### ISSUE THREAD

**Issue by Nekotekina** [dokan-dev/dokany#391]
Hi, I'm experimenting with Dokan. If I run mirror.exe without administrator privileges, trying to run any simple executable from the mounted drive fails with the error 0xC000000D (STATUS_INVALID_PARAMETER). OS: Windows 7 SP1 x64. Executables I tried don't require any privileges.

The questions are (not strictly related to mirror.exe):
1) Why this happens and is it possible to modify mirror sample to fix it?
2) Is it generally possible to run unprivileged executables from virtual filesystems without NTFS features?
#132 seems very related but I failed to find exact answers.

**Comment by Liryna** [comment]
@Nekotekina Hi, 

Can you look into the logs to see when this status is returned?

**Comment by Nekotekina** [comment]
In Dokan logs, there is no such status. This must be process exit status, from Procmon:

19:05:58,5776677	Clockres.exe	11908	Process Start		SUCCESS	Parent PID: 2408
19:05:58,5776710	Clockres.exe	11908	Thread Create		SUCCESS	Thread ID: 10940
19:05:58,5916653	Clockres.exe	11908	Load Image	C:\Windows\System32\ntdll.dll	SUCCESS	Image Base: 0x76ec0000, Image Size: 0x1aa000
19:05:58,5919298	Clockres.exe	11908	Load Image	C:\Windows\SysWOW64\ntdll.dll	SUCCESS	Image Base: 0x770a0000, Image Size: 0x180000
19:05:58,5920283	Clockres.exe	11908	CreateFile	C:\Windows\Prefetch\CLOCKRES.EXE-7D8C1BA1.pf	NAME NOT FOUND	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Attributes: n/a, ShareMode: None, AllocationSize: n/a
19:05:58,5920566	Clockres.exe	11908	Thread Exit		SUCCESS	Thread ID: 10940, User Time: 0.0000000, Kernel Time: 0.0000000
19:05:58,5920710	Clockres.exe	11908	QueryNameInformationFile	C:\Windows\System32\apisetschema.dll	SUCCESS	Name: \Windows\System32\apisetschema.dll
19:05:58,5920876	Clockres.exe	11908	QueryNameInformationFile	\Device\Volume{d6cc17c5-1714-4085-bce7-964f1e9f5de9}\Clockres.exe	SUCCESS	Name: \Clockres.exe
19:05:58,5921033	Clockres.exe	11908	QueryNameInformationFile	C:\Windows\System32\ntdll.dll	SUCCESS	Name: \Windows\System32\ntdll.dll
19:05:58,5921156	Clockres.exe	11908	QueryNameInformationFile	C:\Windows\SysWOW64\ntdll.dll	SUCCESS	Name: \Windows\SysWOW64\ntdll.dll
19:05:58,5924243	Clockres.exe	11908	Process Exit		SUCCESS	Exit Status: -1073741811, User Time: 0.0000000 seconds, Kernel Time: 0.0000000 seconds, Private Bytes: 397 312, Peak Private Bytes: 397 312, Working Set: 245 760, Peak Working Set: 245 760

**Comment by Liryna** [comment]
@Nekotekina I don't have enough information here to help you.
As I can see it work with admin rights and not without. So for me there is at a moment the mirror that return STATUS_INVALID_PARAMETER for a reason.

Is it the mirror or your FS where it happen ? Can you provide the mirror logs ?

**Comment by Nekotekina** [comment]
This is original mirror.exe sample, I mount C:/Test directory with only Clockres.exe file to X: and run it from Explorer. With admin rights it seems OK.

Mirror logs (two files, sorry if too big)
https://gist.github.com/Nekotekina/e2bb2b67fb14998976ccac8c6b503003

**Comment by Liryna** [comment]
@Nekotekina Thank you but this logs are empty 😮  We are the output of the mirror ? This is only dokan library debug messages.

**Comment by Nekotekina** [comment]
Ah sorry. Is this correct log?
https://gist.github.com/Nekotekina/bac7c2da61bb950933530a726d934b0b

**Comment by Liryna** [comment]
There is no error on the mirror logs you are right so I did the test on my windows 10. I was able to run ClockRes.exe && ClockRes64.exe on the mirror with and without admin rights 😢  
https://technet.microsoft.com/en-us/sysinternals/bb897568.aspx

The only difference with running with admin rights the mirror is that all your files are read with admin rights otherwise it does not change the behavior of the FS at all.

Did you compare the procmon ? is there any difference ?
Did you tried other applications ?

**Comment by Nekotekina** [comment]
Maybe it's a problem on my side (if not Win7-specific), I see COMODO reads all executables on startup even if disabled, I'll try to test on VM.

**Comment by Nekotekina** [comment]
Unfortunately, the same results on win7 x64 VM.

Another observation: if I mount a removable drive without admin rights, it works. But it's extremely slow for some reason, it takes about 10 sec of CPU time before the files are available.

**Comment by Liryna** [comment]
I have been able to reproduce the behavior on my win7 VM. It happens with all applications looks like but I have currently not idea why.
Does this happened since always 😮

**Comment by marinkobabic** [comment]
This used to work if the returned filesystemname was NTFS

**Comment by Liryna** [comment]
Fixed with https://github.com/dokan-dev/dokany/pull/392 

Thanks to @Kerbox !

**Comment by DocMAX** [comment]
Still have that issue in Win7 (also with Admin). Win10 works.
